server.port=${PORT:8081}
spring.application.name=category-service

spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=8000
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-init-sql=SELECT 1

spring.jpa.hibernate.ddl-auto=none
spring.main.lazy-initialization=true
spring.sql.init.mode=never